### ISSUE TITLE
Perhaps transition to an ergoemacs theme? 

### ISSUE THREAD

**Issue by mattfidler** [pyluyten/emacs-nu#33]
Now you can ergoemacs-mode can distinguish  between C-m C-[ C-i commands in GUI mode.   Just FYI.   It also applies your basic keys to every mode by lookups and caches.

**Comment by pyluyten** [comment]
hi mattfilder

nu-mode at is core is a keymap.
However it does prompt user. It is like a visual menu.
It assumes one user does not remember 300+ shortcuts.
Still one needs to be able to find the shortcut quickly. More quickly than a standard menu.

so, prompts.
eg when ones enter ctrl-o to open, there are many possibilites
- directly input the key to do something, eg type "ctrl-o o" for helm mini
- use space to have version 1 prompt, then input the key you found
- tab to have another prompt style

and so on.
last time i checked ergoemacs this was different ; 
and it seemed difficult to offer an ergoemacs theme with these prompts

Also i use hooks to adapt popular packages to emacs-nu.
i was not sure ergoemacs theme is correct for this.

so i guess this is closed, but you do a superb job at ergoemacs
so feel free to answer!
